### PR TITLE
Add FilePond

### PR DESCRIPTION
**Pull request by rikschennink**

### CODE REVIEW

**Comment by TixieBorg** [comment]
What do you think of this thumbnail instead? I found the current one a bit too loaded.

FilePond-thumbnail

**Comment by rikschennink** [comment]
Perfectly fine : )

**Comment by TixieBorg** [comment]
Good, could you append your last commit then?

**Comment by rikschennink** [comment]
I think that should be it

**Comment by TixieBorg** [comment]
@rikschennink For the next times, feel free to rebase instead of merge the upstream commits in your fork for a cleaner git tree. Anyway thanks for the contribution, using FilePond at work it's a great tool, very useful, good job!

**Comment by rikschennink** [comment]
@TixieBorg Thanks for the tip! 

I've honestly have never used rebase, so I'm not sure how that works. Will look into it.

It's always amazing to hear others using FilePond, thank you so much for the positive feedback 🙏

**Pull request merged**
